import Footer from "./components/Footer/page";
import Navbar from "./components/Navbar/page";
import "./globals.css";
import { Inter } from "next/font/google";
import NextSessionAuth from "./providers/page";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Clothing Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextSessionAuth>
        <body className={`${inter.className}  antialiased`}>
          <header>
            <Navbar></Navbar>
          </header>

          <main>{children}</main>
          <footer>
            <Footer></Footer>
          </footer>
        </body>
      </NextSessionAuth>
    </html>
  );
}
